const usersData = [
	{
		username: 'admin',
		password: 'ad12343211ad',
		confirmPassword: 'ad12343211ad',
		profilePicture: 'explorer_pic.png',
		name: 'Aria',
		familyName: 'Byte',
		email: 'aria.byte@email.com',
		birthDate: '1992-09-18',
		city: 'Techropolis',
		street: 'Innovation Lane',
		number: '404',
	},
	{
		username: 'songbirdDev',
		password: 'MusiC0d3!',
		confirmPassword: 'MusiC0d3!',
		profilePicture: 'songbird_pic.jpg',
		name: 'Melody',
		familyName: 'Coder',
		email: 'melody.coder@email.com',
		birthDate: '1988-05-03',
		city: 'Harmonyville',
		street: 'Rhythm Street',
		number: '808',
	},
	{
		username: 'pixelPioneer',
		password: 'ArtTech42',
		confirmPassword: 'ArtTech42',
		profilePicture: 'pixel_pioneer_pic.png',
		name: 'Max',
		familyName: 'Canvas',
		email: 'max.canvas@email.com',
		birthDate: '1995-12-12',
		city: 'Pixelburg',
		street: 'Palette Avenue',
		number: '123',
	},
	{
		username: 'quantumCoder',
		password: 'QuantumB1ts!',
		confirmPassword: 'QuantumB1ts!',
		profilePicture: 'quantum_coder_pic.jpg',
		name: 'Quinn',
		familyName: 'Qubit',
		email: 'quinn.qubit@email.com',
		birthDate: '1986-03-28',
		city: 'Bitstream City',
		street: 'Algorithm Street',
		number: '101',
	},
	{
		username: 'astroDev',
		password: 'StellarCode123',
		confirmPassword: 'StellarCode123',
		profilePicture: 'astro_dev_pic.png',
		name: 'Nova',
		familyName: 'Galaxy',
		email: 'nova.galaxy@email.com',
		birthDate: '1998-08-08',
		city: 'Cosmocity',
		street: 'Constellation Lane',
		number: '777',
	},
];

export default usersData;
